const express = require("express");
const cors = require("cors");
require("dotenv").config();
const authRoutes = require("./routes/auth");
const profileRoutes = require("./routes/profile");
const vehicleRoutes = require("./routes/vehicles");
const bookingRoutes = require("./routes/bookings");
const app = express();
app.use(cors());
app.use(express.json());
app.get("/", (req, res) => res.json({ message: "Smart UAE Parking Backend API is running", version: "1.0.0" }));
app.use("/api/auth", authRoutes);
app.use("/api/profile", profileRoutes);
app.use("/api/vehicles", vehicleRoutes);
app.use("/api/bookings", bookingRoutes);
const port = process.env.PORT || 5000;
app.listen(port, () => console.log(`Smart UAE Parking backend running on port ${port}`));
app.use("/api/dda", require("./routes/dda"));
